/* XPM */
static char * 1 [] = {
/* width height ncolors cpp [x_hot y_hot] */
"50 50 5 1 -1 -1",
/* colors */
" 	c Black",
".	c Magenta",
"X	c Cyan",
"o	c Green",
"O	c Red",
/* pixels */
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
"      XXX                                         ",
" ...  XXX                      ooo                ",
" ...  XXX                      ooo                ",
" ...  XXX                      ooo            XXX ",
" ...  XXX            ...       ooo            XXX ",
" ...  XXX       OOO  ...       ooo            XXX ",
" ...  XXX       OOO  ...       ooo            XXX ",
" ...  XXX       OOO  ...       ooo  OOO  ...  XXX "};
