/* XPM */
static char * 1 [] = {
/* width height ncolors cpp [x_hot y_hot] */
"50 50 5 1 -1 -1",
/* colors */
" 	c Black",
".	c Magenta",
"X	c Cyan",
"o	c Green",
"O	c Red",
/* pixels */
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                     XXXXXXXX                     ",
"                     XXXXXXXX                     ",
"                     XXXXXXXX                     ",
"                     XXXXXXXX                     ",
"                     XXXXXXXX                     ",
"                     XXXXXXXX                     ",
"                     XXXXXXXX                     ",
"                     XXXXXXXX                     ",
"                     XXXXXXXX                     ",
"                     XXXXXXXX                     ",
"     ........        XXXXXXXX                     ",
"     ........        XXXXXXXX                     ",
"     ........        XXXXXXXX                     ",
"     ........        XXXXXXXX                     ",
"     ........        XXXXXXXX                     ",
"     ........        XXXXXXXX                     ",
"     ........        XXXXXXXX                     ",
"     ........        XXXXXXXX                     ",
"     ........        XXXXXXXX                     ",
"     ........        XXXXXXXX        oooooooo     "};
